services:
  - type: web
    name: zapbot-ai-manager
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
      - key: PUPPETEER_ARGS
        value: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-gpu"
